apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maksym-shemet-blog-smv-pp-ua
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/maksimshemet/greenhouse_prj.git
    targetRevision: HEAD
    path: prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: greenhouse

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true  
