apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: greenhouse-cert
  namespace: greenhouse
spec:
  secretName: greenhouse-cert # Secret where the certificate will be stored
  duration: 2160h                 # How long the certificate is valid
  renewBefore: 1070h              # When to renew the certificate
  dnsNames:
    - parnyky.smv.pp.ua          # Add additional domains as needed
  issuerRef:
    name: letsencrypt-prod      # The name of your ClusterIssuer or Issuer
    kind: ClusterIssuer 
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: greenhouse-cert
  namespace: greenhouse
spec:
  secretName: greenhouse-cert # Secret where the certificate will be stored
  duration: 2160h                 # How long the certificate is valid
  renewBefore: 1070h              # When to renew the certificate
  dnsNames:
    - api.parnyky.smv.pp.ua          # Add additional domains as needed
  issuerRef:
    name: letsencrypt-prod      # The name of your ClusterIssuer or Issuer
    kind: ClusterIssuer 