apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: greenhouse-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - parnyky.smv.pp.ua
      secretName: greenhouse-cert
  rules:
    - host: parnyky.smv.pp.ua
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: greenhouse-svc
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: greenhouse-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.parnyky.smv.pp.ua
      secretName: greenhouse-cert
  rules:
    - host: api.parnyky.smv.pp.ua
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: greenhouse-api-svc
                port:
                  number: 80